### ISSUE TITLE
Unable to send Multiple Properties apart from Version

### ISSUE THREAD

**Issue by prabhu34** [mkutz/jenkins-google-chat-notification#4]
I need to send few details as part of the chat message properties. By default in your example I can see Version being sent. But when I add new properties, I am getting `groovy.lang.MissingPropertyException: No such property: <property name> for class: groovy.lang.Binding`

Can you guide how to send multiple properties ?

**Comment by prabhu34** [comment]
It was the param value that caused the error. Able to send multiple properties with ease.

**Comment by mkutz** [comment]
Glad you were able to fix it yourself :)
